### ISSUE TITLE
Similar Anime window

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/MyAnime3#1]
Create a new window which shows all the anime which are similar (similar / related / "You may also like")
This functionality is already in JMM Desktop / Anime Buddy

**Comment by ElementalCrisis** [comment]
Are you still planning on implementing this @RickDB?

**Comment by RickDB** [comment]
@ElementalCrisis  Not planned as I'm not sure how to grab this info from the new API.

**Comment by ElementalCrisis** [comment]
@da3dsoul can you add the API call for @RickDB please.

**Comment by da3dsoul** [comment]
Is MyAnime3 in progress for APIv2? You should wait if that's the case, as it's getting a redesign.
Obviously, everything will make it to the API when that happens

**Comment by ElementalCrisis** [comment]
As My Anime 3 is now in maintenance mode, we will not be adding new features and such, this issue is now closed.
