### ISSUE TITLE
Fanart lags behind while fast scrollling

### ISSUE THREAD

**Issue by yhoogi** [ShokoAnime/MyAnime3#34]
In StreamedMP (didn't checked for other yet) display-speed of fanart does not match scrolling speed.
Will result in showing wrong fanart for group (i.e. one of the previous series scrolled through).
Will not be recovered until next group is selected.

MP 1.15.0

**Comment by maxpiva** [comment]
This only happens in the latest version?

**Comment by yhoogi** [comment]
Nope

Is an older bug, but feels like it gotten worse.
As I am now get a liking to raise SPRs I thought I throw it in to the mix. :)

Low prio bug is ok

Cheers,

**Comment by maxpiva** [comment]
Yepz, problem is you can scroll faster than MediaPortal is able to load and render the image. Some tradeoff should be made.

**Comment by RickDB** [comment]
Possibly related to issues #38 as the OnItemSelected event can fire up multiple times and some locking occurs there.

**Comment by yhoogi** [comment]
As issue still exists:
Will this be corrected with the v3.8?

Cheers,

**Comment by ElementalCrisis** [comment]
@maxpiva or @yhoogi, is this still an issue?

**Comment by ElementalCrisis** [comment]
I no longer encounter this issue, is not instant but it does change the fanart after the series poster has loaded. Even switching to multiple series shows the correct fanart.
