### ISSUE TITLE
Shared Playlists for JMM Desktop and MyAnime3

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/MyAnime3#5]
Allow the playlist available in JMM Desktop (stored in the database), to also be used in MyAnime3

**Comment by ElementalCrisis** [comment]
Are you still planning on implementing this @RickDB?

**Comment by RickDB** [comment]
Gonna close this one as to implementing this with stream support as well isn't really possible unless we add some hacks (player doesn't support it atm).
