### ISSUE TITLE
Playback and watched status possible if file was removed

### ISSUE THREAD

**Issue by RickDB** [ShokoAnime/MyAnime3#57]
**Issue** 

Can toggle watch status or start playback even though JMMServer reports them as missing file(s), this results in SQL error for watched toggle and general playback error for playback.

**Resolution** 

Make MA3 aware of file state and disable certain actions.

**Comment by ElementalCrisis** [comment]
Check Desktop as it does this and only lets you update files in your actual collection.

**Comment by RickDB** [comment]
On JMMDesktop the group was still listed but couldn't playback files as they were marked as removed, didn't check watch status however :)

Perhaps MA3 can detect if a file exists on playback start and report back in dialog?
On entering episodes view it normally highlighted them orange (for offline / not available) just not sure if it did that in real time from JMMServer.

**Comment by ElementalCrisis** [comment]
Still an issue @RickDB?
