### ISSUE TITLE
Display Trakt friend activity in MyAnime3

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/MyAnime3#6]
Show recent shouts from friends (or strangers optional) in the following places
- Shouts in Series Info window
- Shouts in Group/Series view when looking at a series
- Shouts in episode list
- Most recent shouts in group filters view / or possibly just show recent activity
- Show activity in continue watching or playlist windows
- Show activity in recommendations windows

**Comment by ElementalCrisis** [comment]
This doesn't seem feasible given the free time @maxpiva and @RickDB have.

Closing for now.
