### ISSUE TITLE
This is all that's left for 3.8

### ISSUE THREAD

**Issue by da3dsoul** [ShokoAnime/MyAnime3#66]
We've got everything else done @maxpiva

**Comment by RickDB** [comment]
@maxpiva Tested today and runs much better now 👍  , bugs found so far:

- Images not loading, only episode thumbnails work but cover / fanart etc.. doesn't:

![image_issue_1](https://user-images.githubusercontent.com/347084/31587764-9ef578ac-b1e7-11e7-9da3-4a50596c9c47.PNG)

- Can't remap local to remote path  as remote path gets converted to only "\":

![local_mapping_issue](https://user-images.githubusercontent.com/347084/31587768-b48a1cc2-b1e7-11e7-8b99-3c51b8d0920f.PNG)

drop folders are included in local mappings but not sure if that's a new issue.

Tested using ShokoServer 3.8.1, need to re-test the others skins as well but started out with the default Mediaportal skin.
MPEI (installer) already fixed as that required some path changes.

**Comment by maxpiva** [comment]
My initial assesment, is that the problem not only lies on Anime3.
Initially most series do not have fanarts, i blamed my import, but
something else smells. Server might have some bug related to myanime3, and
also myanime has some visualization bugs. Tried to squash them, but failed,
will retry later on.

**Comment by RickDB** [comment]
Thanks, tried to debug here as well but didn't come far :(

**Comment by scythe000** [comment]
I'll test as soon as the fix is in place :-)

**Comment by scythe000** [comment]
@maxpiva Any luck?

**Comment by da3dsoul** [comment]
He actually just posted in dev chat today. New computer, so he's been preoccupied getting everything set up.

**Comment by scythe000** [comment]
Bumping for great joy :-).

**Comment by ElementalCrisis** [comment]
@scythe000 

https://forum.team-mediaportal.com/posts/1234827/

**Comment by scythe000** [comment]
Awesome! Thank you. I don’t really have the chops to compile it myself, so I’ll wait for the binary to be posted.

- Sent from my iPhone. I often use speech to text transcription; please excuse any grammatical or spelling errors. -

On Dec 11, 2017, at 11:25 AM, ElementalCrisis <notifications@github.com<mailto:notifications@github.com>> wrote:


@scythe000<https://github.com/scythe000>

https://forum.team-mediaportal.com/posts/1234827/

**Comment by ElementalCrisis** [comment]
Thanks @maxpiva and @RickDB for all your hard work, a little late but we can finally close this issue.
