### ISSUE TITLE
Display problems star ratings

### ISSUE THREAD

**Issue by bertrey** [ShokoAnime/MyAnime3#67]
## Description

I've noticed several display problems with the star ratings on groups/series.
I'm wasn't sure whether I should create separate issues or just one ... I went with one - I hope that's OK.

I have also attached patches for all these issues (separately) [HERE](https://github.com/ShokoAnime/MyAnime3/files/1844468/patches.zip).
I developed these using the Branch_v3.7.1.0 branch (not the master branch), because that was the latest release for MyAnime3.

1.  Missing rating image
Most of the time the star rating image is not displayed.
Only the rating value and the user vote image is displayed:
![screenshot](https://user-images.githubusercontent.com/37740725/37864581-61873188-2f71-11e8-86bf-8a98496424ac.PNG)
It looks like the star rating image just wasn't updated.

2. Incorrect rating image color
(I noticed this after fixing issue 1, but they aren't directly related)
In some cases the stars have the wrong color:
![screenshot](https://user-images.githubusercontent.com/37740725/37864637-f6a3d500-2f71-11e8-995d-f03f53146ff1.PNG)
The problem was that these images are generated in code, and then cached per rating value.
The same cache was used for both rating (blue stars) and vote (white stars).
So if by coincidence the the same value occurs for a rating an a vote (even on different items), they will both use the same image from the cache (which means one of them will have the wrong color).
This was fixed by using different image names for rating/vote images.

3. Scaling issue rating image
On my media center the star rating isn't scaled correctly:
![screenshot](https://user-images.githubusercontent.com/37740725/37864706-eda6cc4a-2f72-11e8-992d-1b99561c720e.PNG)
Changing the windows 10 display scaling from 150% to 100% fixes the problem:
![screenshot setting](https://user-images.githubusercontent.com/37740725/37864729-35e00c7e-2f73-11e8-8545-684a37973127.png)
Strangely enough I can't reproduce the problem on my laptop by setting the display scaling to 150%.
But I found a way to fix this anyway (by modifying the way the image is generated) - and it works on both my mediacenter and my laptop.

4. Wrong case in rating text
This is a _very_ small issue ... but if I'm busy anyway ...
In all 3 screenshots above the votes use a wrong case: it should be `123 votes`, not `123 Votes`.

## Steps to reproduce

1. Start up MediaPortal
2. Open MyAnime3
3. Look at the star rating

## Resolution

As I said before, a patch for all these issues is attached [HERE](https://github.com/ShokoAnime/MyAnime3/files/1844468/patches.zip).
I should probably have done this using a pull request ... but I wasn't sure how to do that :-)

**Comment by ElementalCrisis** [comment]
Thanks for the info and the fix, a pull request is the right way to do it so we can add your changes in. 

Here's what you need to do. 

1. Fork this repo. 
2. Upload your changes in your newly forked repo. 
3. Create a pull request (https://help.github.com/articles/creating-a-pull-request/)

If you need additional help, jump on our Discord Server.

**Comment by ElementalCrisis** [comment]
@bertrey PR was merged in, sorry for the delay. We currently don't have anyone maintaining MA3 as both @maxpiva and @rickdb are busy on other projects. If you'd like to continue helping out, send me a message on Discord.
