### ISSUE TITLE
Sometimes when anime finishes the Epsiode overview stays empty. 

### ISSUE THREAD

**Issue by kusco123** [ShokoAnime/MyAnime3#69]
This happens only sometimes - but when it happens the overall response becomes extremly slow and you need to return to mainscreen before it's starting to behave normal again.

The first effect is that the episode List stays empty.

In teh Log it happens around 12:05

The Setup is:

Shokoserver is running on Synology (2GHZ, 8GB) + Pictures

[309438_MediaPortal-Error.zip](https://github.com/ShokoAnime/MyAnime3/files/2205892/309438_MediaPortal-Error.zip)

**Comment by ElementalCrisis** [comment]
Fixed in https://github.com/ShokoAnime/MyAnime3/commit/3e53ace1bd9906b938d8d24efb37a1cd28ac05ed
