### ISSUE TITLE
MP1.23_Pre seems to break playback

### ISSUE THREAD

**Issue by Yhoogi1** [ShokoAnime/MyAnime3#71]
With update to MP1.23 Pre somehow playback is not possible anymore
Seems like something has changed in the new MP version

Steps to reproduce:
Clicking on an episode does not start playback. Navigation still possible.
I presume either the playback is not executed or immeditately returns

**Comment by Yhoogi1** [comment]
just a question:
Will there be hope that it will be fixed?

Thanks

**Comment by maxpiva** [comment]
Probably, I can take care of this on the weekend.

**Comment by Yhoogi1** [comment]
thanks a lot

**Comment by Yhoogi1** [comment]
Hi there,

Is there still hope?

**Comment by Yhoogi1** [comment]
Many Thanks

Is there somewhere a description what is needed / how to compile the version with the updates?
