### ISSUE TITLE
cant install via extension-manager?

### ISSUE THREAD

**Issue by Andy2244** [ShokoAnime/MyAnime3#73]
I can see the 3.7.3 release via the manager, but on install i just get 404 not found?

**Comment by da3dsoul** [comment]
No offense, but we haven't supported MA3 for years. We don't have any devs who are at all familiar with MP or the MA3 codebase.
If you want to see an MP2 plugin, go put a thumbs up on https://github.com/ShokoAnime/ShokoServer/issues/833. Feel free to comment if you have any input

**Comment by da3dsoul** [comment]
To give an idea, I'm the most active dev going back years now, and I don't know what "extension manager" refers to, nor what URL it's looking for that is now a 404

**Comment by Andy2244** [comment]
Sure i know, was also years i last tried MA3/MP1, but recently i had so many issues with the Kodi-DS player that i wanted to give MP1 a try, since it's still updated.

I just saw the "recent" 2019 release and assumed 3.7.3 should work with MP1, given the last commits by ElementalCrisis?

**Comment by da3dsoul** [comment]
There have been 310 commits since October 27, 2019. Theoretically, it might work with minimal changes, but I have no idea

**Comment by da3dsoul** [comment]
@ElementalCrisis can you see if we can easily build MA3 against Server for this next release, and probably update the URL to whatever changed? I would assume that it's the GitHub move to ShokoAnime, but idk

**Comment by ElementalCrisis** [comment]
Yep, I'll do some testing tonight and see if it works.

**Comment by ElementalCrisis** [comment]
No issues here, able to find and install it via Known Extensions in the MPEM. 

@Andy2244 can you write out what you're doing just in case I'm doing something different? 
@da3dsoul no issues so far, will do some more testing but plugin loads fine and connects to Shoko Server.

**Comment by Andy2244** [comment]
> @Andy2244 can you write out what you're doing just in case I'm doing something different?

Just did a fresh install of MP1, than started the Extension-Manager and updated the repo info twice, since on the first update only 3.7.2 shows up. Than i just click install or select 3.7.3 from the dropdown and get the 404 error.

Will try reinstall again, maybe just a hiccup on my end.

**Comment by Andy2244** [comment]
Alternative can you package the extension as release on github, so i can manually install it, without needing to compile it myself?

**Comment by ElementalCrisis** [comment]
Ah makes sense 3.7.2 errors out as that files was moved to the My Anime 3 archive. I'm in the process of re-organizing our downloads folder and will rebuild update.xml and remove 3.7.2, 

Should have no issues (for now) downloading 3.7.3 and installing it.

**Comment by ElementalCrisis** [comment]
Updated the files and MediaPortal website listing.

**Comment by Andy2244** [comment]
> Updated the files and MediaPortal website listing.

ok tested and working now.

PS: Kinda crazy that good old MP1 is the only media-center i could find with working MadVR + Shoko, but once you are loaded in its actually pretty snappy.

**Comment by da3dsoul** [comment]
MP2 supports madvr, right?

**Comment by Andy2244** [comment]
> MP2 supports madvr, right?

nope... seems the guy that did it for MP1 kinda lost interest, so no MadVR for MP2 atm. There is a request ofc to get it back...
BTW i found this regarding mpc players in a [Emby thread](https://emby.media/community/index.php?/topic/81026-bring-back-madvr/)..... which also once had MadVR support and now they removed it again lol.
Scroll down to the long mpc settings page, this seems promising as a madvr replacement.

**Comment by ElementalCrisis** [comment]
Probably just need to update the version number and rebuild it, I'll do that in a bit.
